# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=11)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=11)),
                ('res_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
